export const INIT_CART = 'SHOPPING_CART.INIT_CART';
export const ADD_CART = 'SHOPPING_CART.ADD_CART';
export const SUB_CART = 'SHOPPING_CART.SUB_CART';
export const REMOVE_CART = 'SHOPPING_CART.REMOVE_CART';
export const RESET_CART = 'SHOPPING_CART.RESET_CART';
