export const AUTH_USER = 'ACCOUNT.AUTH_USER';
export const UNAUTH_USER = 'ACCOUNT.UNAUTH_USER';
export const FETCH_ME = 'ACCOUNT.FETCH_ME';
export const FETCH_ROLES = 'ACCOUNT.FETCH_ROLES';
export const FETCH_MENUS = 'ACCOUNT.FETCH_MENUS';
